sudo: required

env:
  - CONTAINER_NAME=benabs/jenkins

services:
  - docker


script:
  - docker build -t $CONTAINER_NAME .



after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$CONTAINER_NAME";
    fi
