FROM jenkins/jenkins:lts-alpine


# RUN apt-get update \
#       && apt-get install -y sudo curl\
#       && rm -rf /var/lib/apt/lists/*
# RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# # getting the docker-cli
# # --- Attention: docker.sock needs to be mounted as volume in docker-compose.yml
# # see: https://issues.jenkins-ci.org/browse/JENKINS-35025
# # see: https://get.docker.com/builds/
# # see: https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Custom+Build+Environment+Plugin#CloudBeesDockerCustomBuildEnvironmentPlugin-DockerinDocker
# RUN curl -sSL -O https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && tar -xvzf docker-latest.tgz
# RUN mv docker/* /usr/bin/

# USER jenkins


USER root
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk update
RUN apk add --no-cache  \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/main  \
            --repository  http://dl-cdn.alpinelinux.org/alpine/edge/community  \
            openrc docker shadow©


RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
RUN rc-update add docker boot
RUN usermod -aG docker jenkins

USER jenkins
